# Cross toolchain for the version selected by toolchain/env.sh.
set(CMAKE_SYSTEM_NAME WASI)
set(CMAKE_SYSTEM_VERSION 1)
set(CMAKE_SYSTEM_PROCESSOR wasm32)

set(WASIX_SYSROOT "sysroot-exnref-eh" CACHE STRING "WASIX sysroot variant")

set(CMAKE_C_COMPILER "$ENV{WASIXCC_DIR}/bin/wasixcc")
set(CMAKE_CXX_COMPILER "$ENV{WASIXCC_DIR}/bin/wasix++")
set(CMAKE_AR "$ENV{WASIXCC_DIR}/bin/wasixar")
set(CMAKE_RANLIB "$ENV{WASIXCC_DIR}/bin/wasixranlib")
set(CMAKE_NM "$ENV{WASIXCC_DIR}/bin/wasixnm")
set(CMAKE_LINKER "$ENV{WASIXCC_DIR}/bin/wasixld")

set(UNIX 1)
set(WASIX 1)

set(CMAKE_EXECUTABLE_SUFFIX ".wasm")
set(CMAKE_CROSSCOMPILING_EMULATOR "${CMAKE_CURRENT_LIST_DIR}/run-wasix.sh")

set(CMAKE_SYSROOT "$ENV{WASIXCC_SYSROOT_PREFIX}/${WASIX_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_LIBRARY_PATH "${CMAKE_SYSROOT}/lib/wasm32-wasi")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)
